var quotes = new Array(
    "Oh look, ugly naked guy is decorating his Christmas tree! Wow, you should see the size of his Christmas balls! - Phoebe Buffay",
    "Could I be wearing any more clothes? - Joey Tribbiani",
    "They don't know that we know they know we know. - Phoebe Buffay",
    "15 Yemen Road, Yemen. - Janice Litman",
    "Seven. Seven. SEVEN! SEVEN-SEVEN-SEVEN!...seven. - Monica Geller",
    "Custard? Good. Jam? Good. Meat? GOOD. - Joey Tribbiani",
    "They're still not coming on man! And the lotion and powder have made a paste! - Ross Geller",
    "PIVOT! - Ross Geller",
    "How you doin'? - Joey Tribbiani",
    "We were on a break! - Ross Geller",
    "Smelly cat, smelly cat, what are they feeding you? Smelly cat, smelly cat, it's not your fault. - Phoebe Buffay",
    "Isn't that just kick-you-in-the-crotch, spit-on-your-neck fantastic? - Rachel Green",
    "I'm full, and yet I know if I stop eating this, I'll regret it. - Chandler Bing",
    "No, you didn't get me! It's an electric drill, you get me, you kill me! - Chandler Bing",
    "Is it obvious I'm wearing six sweaters? - Joey Tribbiani",
    "You know if you're not careful, you may not get married at all this year. - Chandler Bing",
    "Phoebe. That's, P, as in Phoebe, H, as in hoebe, O as in oebe, E, as in ebe, B, as in bebe, and E as in ... 'Ello there mate. - Phoebe Buffay",
    "I like it even better on you than on Colonel Sanders. - Monica Geller",
    "If you want to receive e-mails about my upcoming shows, then please give me money so I can buy a computer. - Phoebe Buffay",
    "I grew up in a house with Monica, okay. If you didn't eat fast, you didn't eat. - Ross Geller",
    "Your teeth? Yeah, I saw them from outside. - Rachel Green",
    "Because, Phoebe, sometimes after you sleep with someone you have to kill a fish. - Chandler Bing",
    "Uh, so how many cameras are actually on you? - Chandler Bing",
    "I can handle this. Handle is my middle name. Actually, handle is the middle of my first name. - Chandler Bing",
    "Wow. It looks like the Easter Bunny's funeral in here. - Rachel Green",
    "I know! - Monica Geller",
    "I wish I could, but I don't want to. - Phoebe Buffay",
    "Just so you know, it's not that common, it doesn't happen to every guy, and it is a big deal! - Rachel Green",
    "He's a transponster! - Rachel Green",
    "Gum would be perfection. - Chandler Bing",
    "Here come the meat sweats. - Joey Tribbiani",
    "That's right, I stepped up! She's my friend and she needed help. If I had to, I'd pee on any one of you! - Joey Tribbiani",
    "I'm being transferred to Yemen. - Chandler Bing",
    "Welcome to the real world. It sucks. You're going to love it. - Monica Geller",
    "First of all, the customer is always right. A smile goes a long way. And if anyone is ever rude to you: Sneeze Muffin. - Rachel Green",
    "Quick! How do you get a chick out of a VCR? - Chandler Bing",
    "If you have to call me a name, I prefer, 'Ross, The Divorcer.'' It's just cooler. - Ross Geller",
    "Who's FICA and why is he getting all of my money? - Rachel Green",
    "It's actually Miss Chanandler Bong! - Chandler Bing",
    "I'm not great at the advice... can I interest you in a sarcastic comment? Some cheese? - Chandler Bing"
    );

var randIndex = Math.floor((Math.random() * quotes.length)); // generate index value for quote array
document.write(quotes[randIndex]);                           // output quote

